# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_carro_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='ano',
            field=models.IntegerField(default=0, verbose_name=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carro',
            name='modelo',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
